name: Deploy WordPress Theme to Core-X

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Secure copy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "./"
          target: "/home/nowonestudio/domains/nowone.jp/public_html/wp-content/themes/nowone/"
          rm: true
          overwrite: true
          strip_components: 0

          # „Ç¢„ÉÉ„Éó„Åó„Å™„ÅÑ„ÇÇ„ÅÆ
          exclude: |
            .git*
            .github/*
            .vscode/*
            README.md
            deploy.yml

          # üîç „É≠„Ç∞„ÇíË©≥Á¥∞Ë°®Á§∫Ôºà‰ªªÊÑèÔºâ
          debug: true